import { Suspense } from "react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ['400', '500']});

const montserrat = localFont({
  src:'../public/fonts/Montserrat-Regular.ttf',
  variable: '--font-montserrat'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph:{
    title: '...',
    description: '...'
  }
};
  
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <body className={montserrat.variable}>
        <AuthProvider>
          <NavBar />
          <main className="p-5">
            <Suspense fallback={<p>Loading...</p>}>{children}</Suspense>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
